name:                crossword-builder
version:             0.1.0.0
github:              "janeymunoz/crossword-builder"
license:             BSD3
author:              "Janey Muñoz"
maintainer:          "janeemunoz@gmail.com"
copyright:           "Copyright (c) 2018 Janey Muñoz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/janeymunoz/crossword-builder#readme>

dependencies:
- base >= 4.7 && < 5
- protolude
- containers
- text
- gloss

default-extensions:
  - NoImplicitPrelude

library:
  source-dirs: src

executables:
  crossword-builder-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crossword-builder

  crossword-gui-exe: 
    main:                Main.hs
    source-dirs:         gui
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crossword-builder

tests:
  crossword-builder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crossword-builder
